{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "axis-swgi-api.fullname" . }}
spec:
  to:
    kind: Service
    name: {{ include "axis-swgi-api.fullname" . }}
  port:
    targetPort: http
  {{- if .Values.route.host }}
  host: {{ .Values.route.host | quote }}
  {{- end }}
  tls:
    termination: {{ .Values.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}
{{- end }}
